### PR TITLE
Merge non-junction ways in a relation together.

### PR DESCRIPTION
**Pull request by noffle**
These are the first steps toward addressing #1. It handles a very specific
case: where there are multiple LineStrings in a relation, and there are certain
LineStrings that terminate at the head of exactly one other LineString. In this
case, the two are merged into a single LineString.

This does *not* yet handle cases where ways form a fork (geographic) or
junction.

Requesting review (cc @gmaclennan) to make sure I'm on the right track with
this.

### CODE REVIEW

**Comment by gmaclennan** [comment]
I created a basic test line: https://gist.github.com/gmaclennan/413669ae56a397822f3e4afb4de68e3b

**Comment by gmaclennan** [comment]
For polygons, there are two existing libraries that we could use: [topojson](https://github.com/topojson/topojson/) and [mapshaper](https://github.com/mbloch/mapshaper/wiki/Command-Reference#-dissolve). I prefer topojson I think because it's well battle-tested and performant. Mapshaper is more complex code and a more complex API, and I'm not sure about it's memory and performance overhead - we would need to test. It does have an experimental function though to dissolve overlapping polygons, which we may or may not want.

If using topojson, we would convert polygons to a topology, and then use the [`topojson.merge()`](https://github.com/topojson/topojson-client/blob/master/README.md#merge) function.

**Comment by noffle** [comment]
Nice find. I took a look at the code; here are my thoughts:

1. It appears to only handle the case where exactly two LineStrings
   share the same point; not junctions/geographic forks, nor cases where
   a new fork comes out of the midsection of a LineString.
2. It merges properties -- nice.
3. It's great that it handles merging in opposite directions (I didn't
   realize that was desired).
4. How was the base code you used licensed?

I don't see much of a difference between this code and what I've
written, other than the property merging logic (which I'm gleefully
lifting out and into mine now), and the willingness to merge in either
direction. I'll make those changes to my code and push the changes.

**Comment by gmaclennan** [comment]
> 4. How was the base code you used licensed?

Anyway we want. I wrote it... From a side project for processing rivers, I'd forgotten about it.

I don't think handling forks is a big issue. We will generally use this structure (relation of ways) for mapping a large river in multiple segments. In most cases there will be no forks, although some rivers have forks and joins around islands. In the National Hydrgraphic Dataset (NHD, USA) in these cases one of the two lines forks has a property "main channel". We could maybe consider doing that in the future, although it is an edge case - we are unlikely to get to mapping river in that much detail.

btw what I meant my code to do was include segments around a fork in the output, just not dissolved with the other lines. No worries about which code we use, I had that lying around and I thought sharing might be useful.

Ultimately I want to get iD editor to automatically split long ways into relations of smaller ways as you join them - this is a common cause of version forks in the data when two people edit different parts of a long line passing through different areas - both rivers and footpaths / hunting paths. The main purpose of dissolving these lines back into a single line is to easy smoothing/simplification of the line for cartography - if the line is in segments the simplification and smoothing ends up very strange.

**Comment by noffle** [comment]
> I don't think handling forks is a big issue. We will generally use
> this structure (relation of ways) for mapping a large river in
> multiple segments. In most cases there will be no forks, although some
> rivers have forks and joins around islands.

If it's not a big issue I'll omit it for this iteration. At the moment,
it merges one side of the fork and leaves the other as-is.

**Comment by noffle** [comment]
Added a bunch of commits that perform polygon merging inside of relations. Both `@turf/union` and `topojson` implementations are supported. See commit descriptions for more details.

**Comment by noffle** [comment]
This should be good to go, as a start, to begin trying with real datasets.

**Comment by noffle** [comment]
Broke out main logic into https://github.com/noffle/geojson-polygons-equal, https://github.com/noffle/geojson-linestring-dissolve, and https://github.com/noffle/geojson-dissolve.

**Comment by noffle** [comment]
@gmaclennan I think we're ready to try throwing real data at it and start seeing where/if the edge cases lie.

**Comment by gmaclennan** [comment]
Let's rebase this on the PR I just reviewed and throw the Secoya data at it and see what it produces.

**Comment by noffle** [comment]
Status update! I've rebased in the API changes and have the tests passing again.

I'm looking at the Siekopai data, which doesn't do much dissolving right now, since most river polygon pieces aren't linked up under a relation. I experimentally tried adding three river ways to a relation and did an export, and am hitting problems. First it was [a GeoJSON issue](https://github.com/topojson/topojson-client/issues/14) in the output of topojson that `geojsonhint` was unhappy about and thus was omitting from the export.

I wrote some temporary code in `geojson-dissolve` to repair the GeoJSON, but am now seeing render artifacts with the three river segments that did get dissolved together:

dissolve issue

I'm going to examine the ways more closely to try and determine whether it's the data that is malformed in some way, or if it's the dissolving code that's doing something incorrect.

**Comment by noffle** [comment]
Okay. Okay. I think this PR is finally ready to go. I added a few more
commits to fix the lingering bits:

- rewind+lint happens *after* conversion of OsmDocument -> GeoJSON, but
  dissolving happens *before*. I added rewinding and dissolving
  pre-dissolve so that geojson-dissolve doesn't break via topojson on
  malformed GeoJSON input
- osm-p2p-db now (or will shortly) surface deletions. I updated the
  inner bits of the module to accomodate for that

**Pull request merged**
