### PR TITLE
Replace geojsonhint with geojson-validation package

### PR DESCRIPTION
**Pull request by arky**
Quick patch to replace unmaintained '@mapbox/geojsonhint' package [bug #15](https://github.com/digidem/osm-p2p-geojson/issues/15). Resolve the TravisCI build failures [bug #236](https://github.com/digidem/mapeo-desktop/issues/236)

Please kindly review and advice @gmaclennan @noffle . Thanks!

### CODE REVIEW

**Comment by arky** [comment]
@gmaclennan @noffle The tests seems to pass on my gnu/Linux dev machine but fails here. That is very strange.

**Comment by arky** [comment]
@gmaclennan Thanks for fixes! Looking forward for the merge of this pull request.

**Comment by arky** [comment]
**BUMP**

**Comment by noffle** [comment]
Published 4.0.4 (patch release). :tada:

**Comment by noffle** [comment]
Hm, someone already published 4.0.4, but didn't push to `master`? Publishing 4.0.5 just to be safe.

**Pull request merged**
